### ISSUE TITLE
First Desktop Review

### ISSUE THREAD

**Issue by ariel** [basilleaf/luti#28]
Review of implemented desktop video grid.

**Comment by ariel** [comment]
Ariel's Review for 9/21/19:

- Top boundary seems to be set too high; user can navigate above the top row of videos.
- Had issues with video 5,9 not loading but this happened only after keeping the browser window open for a very long time and then navigating around further.
- On load up, first video placement seen is 4,9 , but it should be 4,7 (perhaps happening because of the top boundary issue mentioned above).
- As already identified, boundary for loading videos needs to be broader so that a user can't see the edges of videos loading as they navigate around.
- Set default zoom level to be ~85-90% of what it currently is.
- Only allow user to zoom in twice (we're currently allowing 4 zoom in clicks).

Ariel's action items (addressed in other issues on Github):
- Ariel will create a ring of blank videos around the edge so that users can more properly see the microbes on the current edges.
- Ariel will further evaluate for color corrections on videos.
- Ariel is convinced that "textured" blank videos need to be implemented.

**Comment by mattb** [comment]
Reference image for the grid system:

!(https://user-images.githubusercontent.com/3785/66179652-b022f880-e61e-11e9-883c-5c66ee95e2bc.jpg)
