### ISSUE TITLE
About Page: Wrap video caption text & embed image properly

### ISSUE THREAD

**Issue by ariel** [basilleaf/luti#66]
Ariel needs HTML/CSS help on the About page for 1) making the caption text underneath each video wrap to the width of the video, and 2) making the image file able to display (uploaded to http://lifeundertheice-raw.s3.amazonaws.com/USGS_McMurdoSound_Cropped_Highlighted.png).

**Comment by basilleaf** [comment]
oh I didn't see this ticket but I fixed the video widths when I saw them

could you review and let me know if things still need fixing in there.. 

and for the image not displaying, when I paste url into browser i get access denied, so probably need to go to Amazon s3 admin and "make public" alternatively you can add it as a file in this repo under `public/` and link to it like `href="/USGS_McMurdoSound_Cropped_Highlighted.png"`
